# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - iqtestf

on:
  push:
    branches:
      - azure-deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ecmanagementacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_809c63d490344c70a6ecf1200d316352 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_984226d291264e3d8318ed6506011917 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ecmanagementacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_809c63d490344c70a6ecf1200d316352 }}/ecmanagementacr/socketserver:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'iqtestf'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1c5ee7ec69a34711a1caae58019ce018 }}
        images: 'ecmanagementacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_809c63d490344c70a6ecf1200d316352 }}/ecmanagementacr/socketserver:${{ github.sha }}'